<?php

namespace WSP\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PubblicazioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubblicazioneRepository extends EntityRepository
{
}
