hours_video:
    resource: "@HoursVideoBundle/Controller/"
    type:     annotation
    prefix:   /

wspacl:
    resource: "@WSPACLBundle/Controller/"
    type:     annotation
    prefix:   /

wsp_admin:
    resource: "@WSPAdminBundle/Controller/"
    type:     annotation
    prefix:   /

wsp_promo:
    resource: "@WSPPromoBundle/Controller/"
    type:     annotation
    prefix:   /

jf_acl:
    resource: "@JFACLBundle/Controller/"
    type:     annotation
    prefix:   /
    
jf_core:
    resource: "@JFCoreBundle/Controller/"
    type:     annotation
    prefix:   /
    
ephp_drag_drop:
    resource: "@EphpDragDropBundle/Controller/"
    type:     annotation
    prefix:   /
    
_jf_acl:
    resource: routing_jf_acl.yml

_fos:
    resource: routing_fos.yml
    
# app/config/routing.yml
_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"