security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:    ^/admin
            provider: in_memory
            stateless: true            
            anonymous: ~
            http_basic:
                realm: "Area demo protetta"      
        free:
            pattern:    ^/(promo)?$
            stateless: true            
            anonymous: true
        drag-drop:
            pattern:    ^/drag-drop
            stateless: true            
            anonymous: true
        main:
            #remember_me:
            #    key: divine_office_hub_17021976
            #    lifetime: 31536000 # 365 days in seconds
            #    path: /
            #    domain: ~ # Defaults to the current domain from $_SERVER                   
            #    always_remember_me: true
            #    remember_me_parameter: _remember_me
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                success_handler: my_user_provider        
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    twitter:             "/login/check-twitter"
                login_path:        /login
                failure_path:      /login
                
                success_handler: my_user_provider        
 
                oauth_user_provider:
                    #this is my custom user provider, created from FOSUBUserProvider - will manage the 
                    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
            logout:
                path: /logout
                target: /
                invalidate_session: false # Provissorio per il 5.11
            anonymous:    true
        login:
            pattern:  ^/login$
            security: false
 
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }    
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
