<?php

namespace WSP\PromoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContattiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContattoRepository extends EntityRepository {

    public function nuovi() {
        return $this->createQueryBuilder('c')
                        ->where('c.contattato IS NULL')
                        ->orderBy('c.createdAt', 'DESC');
    }

}
