<?php

namespace WSP\PromoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessaggioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessaggioRepository extends EntityRepository
{
}
