services:
    acl.lock_listener_execute:
        class: JF\ACLBundle\Listener\Lock
        arguments: ["@router", "@service_container", "@security.context"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelRequest }  
