<?php

namespace JF\ACLBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GestoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestoreRepository extends EntityRepository
{
}
