<?php

namespace WSP\ACLBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NegozioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NegozioRepository extends EntityRepository
{
}
